# Generated by Django 5.2.13 on 2026-04-10 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('mutual_fund', 'Mutual Fund'), ('fixed_deposit', 'Fixed Deposit'), ('gold', 'Gold'), ('crypto', 'Crypto'), ('other', 'Other')], default='stock', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
